### ISSUE TITLE
Register Idea - Attach File/URL

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#19]
# Description
* This issue aims to allow a user to link a file or a url to any idea. As a suggestion, in our first version we can allow to attach just a url.

# Project Planning Info
* This Issue is related to WBS's item 1.1.1.1

**Comment by arthurguima** [comment]
Can we use a a HTML text editor in order to do this?
As an example, we could use tinymce:

![image](https://user-images.githubusercontent.com/910049/37831336-dfc98bc0-2e83-11e8-9a09-6bb7c23d8bb6.png)


![image](https://user-images.githubusercontent.com/910049/37831275-a320b0fe-2e83-11e8-8286-bb12318a306d.png)

**Comment by arthurguima** [comment]
The new version of CKEDITOR looks really powerfull too: https://ckeditor.com/

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/10
